catalog-update pipeline
Signed-off-by: Haoyu Sun <hasun@redhat.com>

diff --git a/catalog-update/pipeline.yaml b/catalog-update/pipeline.yaml
--- a/catalog-update/pipeline.yaml
+++ b/catalog-update/pipeline.yaml
@@ -65,6 +65,27 @@ spec:
             description: The branch of the source git repository to clone as starting point for the catalog update
             default: "main"
         steps:
+          - name: check-release-status
+            image: quay.io/hasun/catalog-update:0.0.1
+            script: |
+              set -e
+              oc login --token=${KONFLUX_TOKEN} --server=https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443
+              IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
+              RELEASECONDITIONS=$(kubectl get release "$RELEASE_NAME" -n "$RELEASE_NAMESPACE" \
+              -o jsonpath='{.status.conditions}' | jq '.[] | select(.type == "ManagedPipelineProcessed")')
+              RELEASESTATUS=$(jq -r '.reason' <<< "$RELEASECONDITIONS")
+              if [[ "$RELEASESTATUS" == *"Failed"* ]]; then
+                echo "Release failed, skipping catalog update"
+                exit 1
+              fi
+            env:
+              - name: KONFLUX_TOKEN
+                valueFrom:
+                  secretKeyRef:
+                    name: release-bot-konflux-token
+                    key: konflux-token
+              - name: HOME
+                value: /workspace
           - name: git-clone
             image: quay.io/hasun/catalog-update:0.0.1
             script: |
@@ -77,15 +98,17 @@ spec:
             script: |
               set -e
               oc login --token=${KONFLUX_TOKEN} --server=https://api.stone-prd-rh01.pg1f.p1.openshiftapps.com:6443
-              IFS='/' read -r RELEASE_NAMESPACE RELEASE_NAME <<< "$(params.release)"
+
+              IFS='/' read -r SNAPSHOT_NAMESPACE SNAPSHOT_NAME <<< "$(params.snapshot)"
+              SNAPSHOT_IMAGES=$(oc get snapshot "${SNAPSHOT_NAME}" -n "${SNAPSHOT_NAMESPACE}" \
+              -o jsonpath='{.spec.components}')
 
               cd repo
-              ./hack/bundle_to_catalog.sh -b $(params.snapshot) -n stable,alpha -c lightspeed-catalog-4.15/index.yaml
-              ./hack/bundle_to_catalog.sh -b $(params.snapshot) -n stable,alpha -c lightspeed-catalog-4.16/index.yaml
-              ./hack/bundle_to_catalog.sh -b $(params.snapshot) -n stable,alpha -c lightspeed-catalog-4.17/index.yaml -m
-              ./hack/bundle_to_catalog.sh -b $(params.snapshot) -n stable,alpha -c lightspeed-catalog-4.18/index.yaml -m
-              ./hack/bundle_to_catalog.sh -b $(params.snapshot) -n stable,alpha -c lightspeed-catalog-4.19/index.yaml -m
-
+              ./hack/bundle_to_catalog.sh -b${SNAPSHOT_NAME} -n stable,alpha -c lightspeed-catalog-4.15/index.yaml
+              ./hack/bundle_to_catalog.sh -b${SNAPSHOT_NAME} -n stable,alpha -c lightspeed-catalog-4.16/index.yaml
+              ./hack/bundle_to_catalog.sh -b${SNAPSHOT_NAME} -n stable,alpha -c lightspeed-catalog-4.17/index.yaml -m
+              ./hack/bundle_to_catalog.sh -b${SNAPSHOT_NAME} -n stable,alpha -c lightspeed-catalog-4.18/index.yaml -m
+              ./hack/bundle_to_catalog.sh -b${SNAPSHOT_NAME} -n stable,alpha -c lightspeed-catalog-4.19/index.yaml -m
             workingDir: /workspace
             env:
               - name: KONFLUX_TOKEN
